eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8200


spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    #      properties:
    #        "spring.json.type.mapping": user:vn.iostar.userservice.entity.User
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  application:
    name: friend-service
  data:
    mongodb:
      uri : mongodb+srv://huy:huyvff111@cluster0.wteenm1.mongodb.net/testmongo?retryWrites=true&w=majority
      database : friend-service

springdoc:
  packages-to-scan:
    vn.iostar.friendservice
  api-docs:
    path: /v3/api-docs/friend-service