eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8300


spring:
  elasticsearch:
    # Địa chỉ máy chủ Elasticsearch
    host: localhost
    # Cổng kết nối Elasticsearch
    port: 9200
    # Tên cluster Elasticsearch
    cluster-name: docker-cluster
    # Bật/tắt refresh (mặc định: true)
    refresh: true

  cache:
    type: redis
  application:
    name: group-service
  data:
    elasticsearch:
      repositories:
        auto-create-index: true
    mongodb:
      uri : mongodb+srv://huy:huyvff111@cluster0.wteenm1.mongodb.net/testmongo?retryWrites=true&w=majority
      database : group-service

springdoc:
  packages-to-scan:
    vn.iostar.groupservice
  api-docs:
    path: /v1/api-docs/group-service