eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8300


spring:
  application:
    name: group-service
  data:
    mongodb:
      uri : mongodb+srv://huy:huyvff111@cluster0.wteenm1.mongodb.net/testmongo?retryWrites=true&w=majority
      database : group-service

springdoc:
  packages-to-scan:
    vn.iostar.groupservice
  api-docs:
    path: /v3/api-docs/group-service