eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8300


spring:
  cache:
    type: redis
  application:
    name: group-service
  data:
    mongodb:
      uri : mongodb+srv://huy:huyvff111@cluster0.wteenm1.mongodb.net/testmongo?retryWrites=true&w=majority
      database : group-service
    redis:
      host: redis-18198.c100.us-east-1-4.ec2.redns.redis-cloud.com
      port: 18198
      password: CnbRHEYhr9xFnvV75vOSPYZXp0KVTSaI

springdoc:
  packages-to-scan:
    vn.iostar.groupservice
  api-docs:
    path: /v1/api-docs/group-service