server:
    port: 8888
spring:
    application:
        name: config_server
    cloud:
        config:
          server:
            git:
              uri: https://github.com/81Quanghuy/cloud-config-server.git
              default-label: main
              clone-on-start: true
              skip-ssl-validation: false



