
server:
  port: 8888

spring:
  profiles:
    active: default
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/81Quanghuy/cloud-config-server.git
          basedir: /tmp/cloud-config-repo