server:
    port: 8888
spring:
    application:
        name: cloud-config-server
    profiles:
      active: default
    cloud:
        config:
          server:
            git:
              uri: https://github.com/81Quanghuy/cloud-config-server.git
              skip-ssl-validation: true
              default-label: main



